server:
  port: 9998

# Redis 配置
spring:
  redis:
    # Redis 数据库索引(默认为 0)
    database: 0
    # Redis 服务器地址
    host: 127.0.0.1
    # 服务器端口
    port: 6379
    # Redis 数据库密码（默认为空）
    password:
    pool:
      lettuce:
        # 连接池最大连接数（负数表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
        # 连接池中最大空闲连接
        max-idle: 8
        # 连接池中最小空闲连接
        min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 500ms